apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: k8s-tin-gg-tls
spec:
  secretName: k8s-tin-gg
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: k8s.tin.gg
  dnsNames:
    - k8s.tin.gg
    # - www.k8s.tin.gg
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - k8s.tin.gg
          # - www.k8s.tin.gg